"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _greeting from './greeting.bones.json'

configureBoneyard({"color":"#171717","darkColor":"#0a0a0a","animate":"pulse","transition":300})

registerBones({
  "greeting": _greeting,
})
